import '../styles/globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from "react";
import MainLayout from "@/components/layouts/MainLayouts/MainLayout";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Vegas Main',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <MainLayout>
                    {children}
                </MainLayout>
            </body>
        </html>
    )
}
